# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c2d919029b07716e6b8a221c7a0b5f3b2d50457576ac5f94abe66b584d1df4eb5c3a501ecfee4c502b36236038586cc64ea3a9570e1b0b93b8a782a009ea6da

test:
  secret_key_base: 644b21027fa154f055d90a556e73517d0fa6d15dc67480c555a45e18d1242d00721a085af21f618e9dd0e3114896c72752449ef9f676f5b66c076f47540d0a38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
